title: Caixing Wang's Homepage
page-top-title: Caixing Wang
top-section-bg-text: Welcome to my homepage!
home-subtitle: Caixing Wang
copyright-text: '&copy; Caixing Wang 2023-2024. All Rights Reserved.'
